# Generated by Django 2.1.3 on 2018-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='price',
            field=models.FloatField(),
        ),
    ]
